version: '3.4'

services:
  api:
    container_name: bojobox_api
    image: ${DOCKER_REGISTRY}bojoboxapi
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
    - "8000:80" 
    # environment:
    # - SQLSERVER_HOST=172.17.0.2
    network_mode: bridge