version: '3.4'

services:
  api:
    container_name: bojobox_api
    image: ${DOCKER_REGISTRY}bojoboxapi
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
    - "8000:80" 
    network_mode: bridge